services:
  wish-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wish-react-app:latest
    container_name: wish-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
